version: '3'

services: 
    logger:
        container_name: termperature-logger
        build: /home/pi/temperature/logger/
        volumes:
            - "/home/pi/temperature/database:/logger/temperatures.db"
        environment:
            TZ: "Australia/Sydney"
            DATABASE_LOCATION: "/logger/temperatures.db"
            DEVICE_ADDRESS: "192.168.1.4"
            SENSORS: "Temperature-Sensor_1,Temperature-Sensor_2,Temperature-Sensor_3"
        restart: unless-stopped

    chart:
        container_name: temperature-chart
        build: /home/pi/temperature/chart/
        ports:
            - "5000:5000/tcp"
        volumes: 
            - "/home/pi/temperature/database:/logger/temperatures.db"
        environment: 
            TZ: "Australia/Sydney"
            DATABASE_LOCATION: "/logger/temperatures.db"
            SENSOR_ADDRESS: "192.168.1.6"
        restart: unless-stopped
