version: '3'

services: 
    logger:
        container_name: termperature-logger
        build: /home/pi/temperature/logger/
        volumes:
            - "/home/pi/temperature/database:/logger/temperatures.db"
        environment: 
            TZ: "Australia/Sydney"
            DATABASE_LOCATION: /logger/temperatures.db
            PROTOCOL_TYPE: MQTT # Also available HTTP
            SENSOR_CHANNEL: Temperature-Sensor_1/SHT30 # Required for MQTT, expects subchannels /Temperature and /Humidity
            SENSOR_ADDRESS: "192.168.1.6"
        restart: unless-stopped
    
    chart:
        container_name: temperature-chart
        build: /home/pi/temperature/chart/
        ports:
            - "5000:5000/tcp"
        volumes: 
            - "/home/pi/temperature/database:/logger/temperatures.db"
        environment: 
            TZ: "Australia/Sydney"
            DATABASE_LOCATION: /logger/temperatures.db
            SENSOR_ADDRESS: "192.168.1.6"
        restart: unless-stopped
